[package]
name = "saka-mgrep"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "simple commandline utility to search contents in file"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
