[package]
name = "deltalake_setup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deltalake = "0.19.1"
tokio = "1.40.0"
