name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Tutorials
      run: cargo build --verbose --manifest-path tutorials/Cargo.toml
    - name: Run Tutorials tests
      run: cargo test --verbose --manifest-path tutorials/Cargo.toml
    - name: Build Workspaces
      run: cargo build --verbose --manifest-path Cargo.toml
    - name: Run Workspaces tests
      run: cargo test --verbose --manifest-path Cargo.toml
