[workspace]

members = [
    "adder",
    "smart_pointers",
    "add_one",
    "pointer_deref",
    "pointer_drop",
    "reference_counter",
    "interior_mut",
    "tree_node",
    "rc_memory_leak",
]
